#!/usr/bin/env bash
# Stop hook: keep docs/learning-map.md's Status column in sync with the phase
# exit criteria in docs/roadmap.md.
#
# A phase is complete when every "- [ ]" under its "## Phase N" heading has
# become "- [x]". That is mechanically decidable, so this hook decides it and
# updates the status table itself rather than nagging about it.
#
# What it deliberately does NOT do: write the "What it taught" prose. That is
# the actual value of the learning map and cannot be generated by sed -- a
# hook that invented a summary would produce something worse than nothing.
# It flips the status, then asks Claude for the write-up.
#
# No jq dependency (not installed on this machine). Always exits 0: a Stop hook
# failing non-zero would interfere with the turn ending.
#
# Writes to exactly one file, docs/learning-map.md. It never commits, never
# pushes, and never touches source.

set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR" 2>/dev/null || exit 0

ROADMAP="docs/roadmap.md"
MAP="docs/learning-map.md"

# Silent unless both documents exist -- this hook is meaningless without them.
[[ -f "$ROADMAP" && -f "$MAP" ]] || exit 0

# --- which phases have every box ticked? --------------------------------------
# Walk the roadmap associating each checkbox with the phase heading above it.
# A phase counts as complete only if it has at least one criterion and none
# are unticked. "at least one" matters: a phase whose section has no checkboxes
# yet would otherwise report complete on an empty set.
#
# Deferred phases (5b) are skipped -- optional work should not auto-complete.
complete_phases=$(
  awk '
    /^## Phase [0-9]+[a-z]? / {
      phase = $3
      sub(/[^0-9a-z]+$/, "", phase)
      total[phase] = total[phase] + 0
      next
    }
    /^- \[x\]/ { if (phase != "") { total[phase]++; done[phase]++ } ; next }
    /^- \[ \]/ { if (phase != "") { total[phase]++ } ; next }
    END {
      for (p in total) {
        if (total[p] > 0 && total[p] == done[p]) print p
      }
    }
  ' "$ROADMAP" 2>/dev/null | sort -u
)

[[ -z "$complete_phases" ]] && exit 0

# --- flip Pending -> Complete for those phases in the topic table -------------
# Table rows look like:
#   | 1 | Core Java, ... | 1 | Pending |
# The phase cell is the second-to-last field and may list several phases
# ("0, 5"), so a row is updated only when every phase it depends on is done.
today=$(date +%Y-%m-%d)
updated_phases=""

for phase in $complete_phases; do
  # Rows still Pending whose phase cell mentions this phase.
  matching=$(awk -F'|' -v p="$phase" '
    /^\|/ && $0 ~ /Pending/ {
      phases = $(NF-2)
      gsub(/[[:space:]]/, "", phases)
      n = split(phases, parts, ",")
      for (i = 1; i <= n; i++) if (parts[i] == p) { print NR; break }
    }
  ' "$MAP" 2>/dev/null)

  [[ -z "$matching" ]] && continue

  for lineno in $matching; do
    # Only complete a row when ALL phases it spans are complete. A topic
    # taught across phases 0 and 5 is not learned when only 0 is done.
    row_phases=$(awk -F'|' -v n="$lineno" 'NR == n { p = $(NF-2); gsub(/[[:space:]]/, "", p); print p }' "$MAP")
    all_done=1
    IFS=',' read -ra parts <<< "$row_phases"
    for part in "${parts[@]}"; do
      grep -qx "$part" <<< "$complete_phases" || all_done=0
    done
    (( all_done == 0 )) && continue

    # Replace the final "Pending" cell on this row only.
    sed -i "${lineno}s/| Pending |/| Complete |/" "$MAP" 2>/dev/null
  done

  # Mark the phase's own section heading, if still pending.
  if grep -qE "^## Phase ${phase} .*· Pending$" "$MAP" 2>/dev/null; then
    sed -i -E "s/^(## Phase ${phase} .*)· Pending$/\1· **Complete** (${today})/" "$MAP" 2>/dev/null
    updated_phases="${updated_phases}${phase} "
  fi
done

[[ -z "$updated_phases" ]] && exit 0

updated_phases="${updated_phases% }"

msg="Phase ${updated_phases} complete -- docs/learning-map.md status updated. The 'What it taught' write-up is still needed."
ctx="Every exit criterion for Phase ${updated_phases} is now ticked in docs/roadmap.md, and the Stop hook has already flipped the corresponding Status cells and the phase heading in docs/learning-map.md to Complete. What it has NOT written, because a shell script cannot, is the 'What it taught' prose for that phase's section. Offer to write it: concrete lessons from what actually happened during the phase -- surprises, bugs whose root cause was instructive, decisions that turned out wrong -- not a restatement of what was built. Keep the existing sections' voice. Do not commit it unless the user asks."

# --- emit ---------------------------------------------------------------------
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

printf '{"systemMessage":"learning-map: %s","hookSpecificOutput":{"hookEventName":"Stop","additionalContext":"%s"}}\n' \
  "$(esc "$msg")" "$(esc "$ctx")"

exit 0
